// kws-soc based on Hazard3 implementation of tb_cxxrtl


#include <iostream>
#include <fstream>
#include <cstdint>
#include <string>
#include <stdio.h>
#include <queue>

#include <unistd.h>
#include <sys/socket.h>
#include <netinet/in.h>

#include "sim/i2s_mic_sim.h"

// Device-under-test model generated by CXXRTL:
#include "dut.cpp"
#include <cxxrtl/cxxrtl_vcd.h>

// TODO: Delte todo or make this emit an error if not defined
#ifndef CLK_MHZ
    #error "CLK_MHZ is not defined. Check your Makefile variables!"
#endif
#ifndef UART_BAUD_RATE
    #error "UART_BAUD_RATE is not defined. Check your Makefile variables!"
#endif

#define UART_IDLE 0
#define UART_START 1
#define UART_STOP 9

// There must be a better way
#ifdef __x86_64__
#define I64_FMT "%ld"
#else
#define I64_FMT "%lld"
#endif

// -----------------------------------------------------------------------------

const char *help_str =
"Usage: kws_soc_tb [--port n] [--vcd x.vcd] [--cycles n] \\\n"
"                      [--jtagdump x] [--jtagreplay x]\n"
"\n"
"    --vcd x.vcd      : Path to dump waveforms to\n"
"    --cycles n       : Maximum number of cycles to run before exiting.\n"
"                       Default is 0 (no maximum).\n"
"    --port n         : Port number to listen for openocd remote bitbang. Sim\n"
"                       runs in lockstep with JTAG bitbang, not free-running.\n"
"    --jtagdump       : Dump OpenOCD JTAG bitbang commands to a file so they\n"
"                       can be replayed. (Lower perf impact than VCD dumping)\n"
"    --jtagreplay     : Play back some dumped OpenOCD JTAG bitbang commands\n"
;

void exit_help(std::string errtext = "") {
	std::cerr << errtext << help_str;
	exit(-1);
}

int wait_for_connection(int server_fd, uint16_t port, struct sockaddr *sock_addr, socklen_t *sock_addr_len) {
	int sock_fd;
	printf("Waiting for connection on port %u\n", port);
	if (listen(server_fd, 3) < 0) {
		fprintf(stderr, "listen failed\n");
		exit(-1);
	}
	sock_fd = accept(server_fd, sock_addr, sock_addr_len);
	if (sock_fd < 0) {
		fprintf(stderr, "accept failed\n");
		exit(-1);
	}
	printf("Connected\n");
	return sock_fd;
}

static const int TCP_BUF_SIZE = 256;

// Simple UART character buffer
std::queue<char> uart_tx_queue;
std::queue<char> uart_rx_queue;

int main(int argc, char **argv) {

    std::string mic_hex_path = ""; 
	bool dump_waves = false;
	std::string waves_path;
	int64_t max_cycles = 0;
	uint16_t port = 0;
	bool dump_jtag = false;
	std::string jtag_dump_path;
	bool replay_jtag = false;
	std::string jtag_replay_path;

	for (int i = 1; i < argc; ++i) {
		std::string s(argv[i]);
		if (s.rfind("--", 0) != 0) {
			std::cerr << "Unexpected positional argument " << s << "\n";
			exit_help("");
		}
		else if (s == "--vcd") {
			if (argc - i < 2)
				exit_help("Option --vcd requires an argument\n");
			dump_waves = true;
			waves_path = argv[i + 1];
			i += 1;
		}
		else if (s == "--jtagdump") {
			if (argc - i < 2)
				exit_help("Option --jtagdump requires an argument\n");
			dump_jtag = true;
			jtag_dump_path = argv[i + 1];
			i += 1;
		}
		else if (s == "--jtagreplay") {
			if (argc - i < 2)
				exit_help("Option --jtagreplay requires an argument\n");
			replay_jtag = true;
			jtag_replay_path = argv[i + 1];
			i += 1;
		}
		else if (s == "--cycles") {
			if (argc - i < 2)
				exit_help("Option --cycles requires an argument\n");
			max_cycles = std::stol(argv[i + 1], 0, 0);
			i += 1;
		}
		else if (s == "--port") {
			if (argc - i < 2)
				exit_help("Option --port requires an argument\n");
			port = std::stol(argv[i + 1], 0, 0);
			i += 1;
		}
        else if (s == "--mic") { 
			if (argc - i < 2)
				exit_help("Option --mic requires an argument\n");
			mic_hex_path = argv[i + 1];
			i += 1;
		}
		else {
			std::cerr << "Unrecognised argument " << s << "\n";
			exit_help("");
		}
	}
	if (port == 0 && !replay_jtag)
		exit_help("At least one of --port or --jtagreplay must be specified.\n");
	if (dump_jtag && port == 0)
		exit_help("--jtagdump specified, but there is no JTAG socket to dump from.\n");
	if (replay_jtag && port != 0)
		exit_help("Can't specify both --port and --jtagreplay\n");

	int server_fd, sock_fd;
	struct sockaddr_in sock_addr;
	int sock_opt = 1;
	socklen_t sock_addr_len = sizeof(sock_addr);
	char txbuf[TCP_BUF_SIZE], rxbuf[TCP_BUF_SIZE];
	int rx_ptr = 0, rx_remaining = 0, tx_ptr = 0;

	if (port != 0) {
		server_fd = socket(AF_INET, SOCK_STREAM, 0);
		if (server_fd == 0) {
			fprintf(stderr, "socket creation failed\n");
			exit(-1);
		}

		int setsockopt_rc = setsockopt(
			server_fd, SOL_SOCKET, SO_REUSEADDR | SO_REUSEPORT,
			&sock_opt, sizeof(sock_opt)
		);

		if (setsockopt_rc) {
			fprintf(stderr, "setsockopt failed\n");
			exit(-1);
		}

		sock_addr.sin_family = AF_INET;
		sock_addr.sin_addr.s_addr = INADDR_ANY;
		sock_addr.sin_port = htons(port);
		if (bind(server_fd, (struct sockaddr *)&sock_addr, sizeof(sock_addr)) < 0) {
			fprintf(stderr, "bind failed\n");
			exit(-1);
		}

		sock_fd = wait_for_connection(server_fd, port, (struct sockaddr *)&sock_addr, &sock_addr_len);
	}

	std::ofstream jtag_dump_fd;
	if (dump_jtag) {
		jtag_dump_fd.open(jtag_dump_path);
		if (!jtag_dump_fd.is_open()) {
			std::cerr << "Failed to open \"" << jtag_dump_path << "\"\n";
			return -1;
		}
	}

	std::ifstream jtag_replay_fd;
	if (replay_jtag) {
		jtag_replay_fd.open(jtag_replay_path);
		if (!jtag_replay_fd.is_open()) {
			std::cerr << "Failed to open \"" << jtag_replay_path << "\"\n";
			return -1;
		}
	}

	cxxrtl_design::p_kws__soc top;

    I2SMicSim i2s_mic(0x00000000);
    if (!mic_hex_path.empty()) {
        printf("Loading mic audio from %s\n", mic_hex_path.c_str());
        i2s_mic.load_hex_file(mic_hex_path);
    } else {
        printf("Warning: No --mic file provided. Mic will output 0x00.\n");
    }

	std::ofstream waves_fd;
	cxxrtl::vcd_writer vcd;
	if (dump_waves) {
		waves_fd.open(waves_path);
		cxxrtl::debug_items all_debug_items;
		top.debug_info(&all_debug_items, /*scopes=*/nullptr, "");
		vcd.timescale(1, "us");
		vcd.add(all_debug_items);
	}

	// Reset + initial clock pulse
	top.step();
	top.p_clk.set<bool>(true);
	top.p_tck.set<bool>(true);
	top.step();
	top.p_clk.set<bool>(false);
	top.p_tck.set<bool>(false);
	top.p_trst__n.set<bool>(true);
	top.p_rst__n.set<bool>(true);
	top.p_uart__rx.set<bool>(true);  // UART idle high
	top.step();
	top.step(); // workaround for github.com/YosysHQ/yosys/issues/2780

	bool timed_out = false;
	bool uart_tx_prev = true;

	for (int64_t cycle = 0; cycle < max_cycles || max_cycles == 0; ++cycle) {
		top.p_clk.set<bool>(false);
		top.step();
		if (dump_waves)
			vcd.sample(cycle * 2);
		top.p_clk.set<bool>(true);
		top.step();
		top.step(); // workaround for github.com/YosysHQ/yosys/issues/2780

		// UART TX monitoring (print to console)
		bool uart_tx = top.p_uart__tx.get<bool>();
		static int uart_state = UART_IDLE; // 0=idle, 1=start, 2-9=data, 10=stop
		static int uart_bit_timer = 0;
		static int uart_shifter = 0;
		const int uart_cycles_per_bit = (int)((CLK_MHZ * 1000000.0) / UART_BAUD_RATE);

		if (uart_state == UART_IDLE) {
			if (!uart_tx) {
				uart_state = UART_START;
				uart_bit_timer = uart_cycles_per_bit + uart_cycles_per_bit / 2; // Wait 1.5 bit periods to sample middle of first data bit
			}
		} else {
			if (--uart_bit_timer == 0) {
				// if the uart is not idle, we are receiving data
				if (uart_state >= UART_START && uart_state < UART_STOP) {
					// shift the bit into our int buffer as long as uart_tx is up
					uart_shifter |= (uart_tx ? 1 : 0) << (uart_state - 1);
					uart_bit_timer = uart_cycles_per_bit;
					uart_state++;
				} else if (uart_state == UART_STOP) {
					// if you want to be accurate, you should wait for the stop bit to finish
					// but for simple print it's fine.
					printf("%c", (char)uart_shifter);
					fflush(stdout);
					uart_shifter = 0;
					uart_state = UART_IDLE;
				}
			}
		}
		uart_tx_prev = uart_tx;

        // ---- I2S MIC MODEL EVALUATION ----
        // Adjust these pin names to whatever your CXXRTL model exposed
        bool i2s_sck = top.p_sck__out.get<bool>();
        bool i2s_ws  = top.p_ws__out.get<bool>();
        
        bool i2s_sd = i2s_mic.step(i2s_sck, i2s_ws);
        top.p_sd.set<bool>(i2s_sd);

		// JTAG handling (same as tb.cpp)
		bool got_exit_cmd = false;
		bool step = false;
		if (port != 0 || replay_jtag) {
			while (!step) {
				if (rx_remaining > 0) {
					char c = rxbuf[rx_ptr++];
					--rx_remaining;

					if (c == 'r' || c == 's') {
						top.p_trst__n.set<bool>(true);
						step = true;
					}
					else if (c == 't' || c == 'u') {
						top.p_trst__n.set<bool>(false);
					}
					else if (c >= '0' && c <= '7') {
						int mask = c - '0';
						top.p_tck.set<bool>(mask & 0x4);
						top.p_tms.set<bool>(mask & 0x2);
						top.p_tdi.set<bool>(mask & 0x1);
						step = true;
					}
					else if (c == 'R') {
						txbuf[tx_ptr++] = top.p_tdo.get<bool>() ? '1' : '0';
						if (tx_ptr >= TCP_BUF_SIZE || rx_remaining == 0) {
							send(sock_fd, txbuf, tx_ptr, 0);
							tx_ptr = 0;
						}
					}
					else if (c == 'Q') {
						printf("OpenOCD sent quit command\n");
						got_exit_cmd = true;
						step = true;
					}
				}
				else {
					if (tx_ptr > 0) {
						send(sock_fd, txbuf, tx_ptr, 0);
						tx_ptr = 0;
					}
					rx_ptr = 0;
					if (replay_jtag) {
						rx_remaining = jtag_replay_fd.readsome(rxbuf, TCP_BUF_SIZE);
					}
					else {
						rx_remaining = read(sock_fd, &rxbuf, TCP_BUF_SIZE);
					}
					if (dump_jtag && rx_remaining > 0) {
						jtag_dump_fd.write(rxbuf, rx_remaining);
					}
					if (rx_remaining == 0) {
						if (port == 0) {
							got_exit_cmd = true;
						}
						else {
							sock_fd = wait_for_connection(server_fd, port, (struct sockaddr *)&sock_addr, &sock_addr_len);
						}
					}
				}
			}
		}

		if (dump_waves) {
			top.step();
			vcd.sample(cycle * 2 + 1);
			waves_fd << vcd.buffer;
			vcd.buffer.clear();
		}

		if (cycle + 1 == max_cycles) {
			printf("Max cycles reached\n");
			timed_out = true;
		}
		if (got_exit_cmd)
			break;
	}

	if (port != 0) {
		close(sock_fd);
	}
	if (dump_jtag) {
		jtag_dump_fd.close();
	}
	if (replay_jtag) {
		jtag_replay_fd.close();
	}

	return 0;
}
