#!/usr/bin/env bash
# Generate a Cyclone V fractional-N PLL via the Quartus CLI (qsys-script
# + qsys-generate).  Use this when the integer-N gen_pll.py can't hit the
# target frequency exactly — e.g. 36.864 MHz, which would land cfg_div=17
# at exactly 16,000 Hz raw I2S frame rate.
#
# Usage:
#     scripts/gen_pll_frac.sh <CLK_MHZ_FLOAT> [DEVICE_FAMILY] [DEVICE_PART]
#
# Example:
#     scripts/gen_pll_frac.sh 36.864
#     scripts/gen_pll_frac.sh 49.152 "Cyclone V" 5CSXFC6D6F31C6
#
# Output: quartus/ip/clock_pll_gen_frac/clock_pll_gen.{qsys,qip,v}
#
# Requires Quartus 25.1+ (qsys-script and qsys-generate under
# $QUARTUS_ROOTDIR/sopc_builder/bin/).
set -euo pipefail

CLK_MHZ=${1:-}
DEVICE_FAMILY=${2:-"Cyclone V"}
DEVICE_PART=${3:-"5CSXFC6D6F31C6"}

if [[ -z "$CLK_MHZ" ]]; then
    echo "usage: $0 <CLK_MHZ_FLOAT> [DEVICE_FAMILY] [DEVICE_PART]" >&2
    exit 2
fi

# Locate qsys-script / qsys-generate.  Quartus puts them under
# sopc_builder/bin (separate from the main quartus/bin used by the rest
# of the flow), so PATH-based which often misses them.
QUARTUS_ROOTDIR=${QUARTUS_ROOTDIR:-/home/public/Quartus-Installed/quartus}
QSYS_BIN="$QUARTUS_ROOTDIR/sopc_builder/bin"
if [[ ! -x "$QSYS_BIN/qsys-script" ]]; then
    echo "ERROR: qsys-script not found under $QSYS_BIN." >&2
    echo "       Set QUARTUS_ROOTDIR to your Quartus installation root." >&2
    exit 1
fi

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="$ROOT_DIR/quartus/ip/clock_pll_gen_frac"
WORK_DIR=$(mktemp -d)
trap 'rm -rf "$WORK_DIR"' EXIT

echo "[gen_pll_frac] CLK_MHZ=$CLK_MHZ FAMILY='$DEVICE_FAMILY' PART=$DEVICE_PART"
echo "[gen_pll_frac] work=$WORK_DIR  out=$OUT_DIR"

# Tcl script: build a one-instance Qsys system around altera_pll in
# fractional-N mode.  Module is named clock_pll_gen so the rest of the
# repo can drop-in replace ALTPLL_25.
cat > "$WORK_DIR/gen.tcl" <<EOF
package require -exact qsys 25.1
# Inner system name: chosen so it can't collide with the legacy ALTPLL
# wrapper module name `clock_pll_gen`.  We hand-write a port-adapter
# `clock_pll_gen` wrapper below that maps the qsys system's exports
# (refclk_clk / refclk_rst_reset / outclk0_clk / locked_export) onto
# the legacy port names (inclk0 / areset / c0 / locked) that
# quartus/fpga_top.v already drives.
create_system clock_pll_gen_inner
set_project_property DEVICE_FAMILY  {$DEVICE_FAMILY}
set_project_property DEVICE         {$DEVICE_PART}

add_instance pll altera_pll
set_instance_parameter_value pll gui_reference_clock_frequency  50.0
set_instance_parameter_value pll gui_pll_mode                   {Fractional-N PLL}
set_instance_parameter_value pll gui_number_of_clocks           1
set_instance_parameter_value pll gui_operation_mode             direct
set_instance_parameter_value pll gui_use_locked                 1
set_instance_parameter_value pll gui_active_clk                 0
set_instance_parameter_value pll gui_output_clock_frequency0    $CLK_MHZ

add_interface refclk     clock sink
add_interface refclk_rst reset sink
add_interface outclk0    clock source
add_interface locked     conduit end

set_interface_property refclk     EXPORT_OF pll.refclk
set_interface_property refclk_rst EXPORT_OF pll.reset
set_interface_property outclk0    EXPORT_OF pll.outclk0
set_interface_property locked     EXPORT_OF pll.locked

save_system clock_pll_gen_inner.qsys
EOF

# Run qsys-script from inside WORK_DIR so the .qsys lands there.
( cd "$WORK_DIR" && "$QSYS_BIN/qsys-script" --script=gen.tcl )

# Generate synthesis HDL.
"$QSYS_BIN/qsys-generate" "$WORK_DIR/clock_pll_gen_inner.qsys" \
    --synthesis=VERILOG \
    --output-directory="$WORK_DIR/out" \
    --family="$DEVICE_FAMILY" \
    --part="$DEVICE_PART" \
    > "$WORK_DIR/qsys-gen.log" 2>&1 || {
    echo "ERROR: qsys-generate failed; see $WORK_DIR/qsys-gen.log" >&2
    cat "$WORK_DIR/qsys-gen.log" >&2
    exit 1
}

# Move the generated tree into place.
rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR"
cp -r "$WORK_DIR/out/synthesis"/* "$OUT_DIR/"
cp "$WORK_DIR/clock_pll_gen_inner.qsys" "$OUT_DIR/"

# Hand-written port adapter: present the legacy ALTPLL_25 port names
# (inclk0 / areset / c0 / locked) so quartus/fpga_top.v's existing
# `clock_pll_gen my_pll(.inclk0(...), ...)` instantiation works
# untouched whether the integer-N or fractional-N script generated it.
cat > "$OUT_DIR/clock_pll_gen.v" <<'EOFADAPTER'
// clock_pll_gen — port adapter around the qsys-generated fractional-N PLL.
//
// The inner module (clock_pll_gen_inner, generated by qsys-generate
// from the .qsys file in this directory) exposes the modern Avalon-MM
// PLL interface signals (refclk_clk / refclk_rst_reset / outclk0_clk /
// locked_export).  The rest of the SoC top-level was written for the
// legacy ALTPLL_25 port names (inclk0 / areset / c0 / locked).
//
// This thin wrapper translates between the two so a fractional CLK_MHZ
// (e.g. 36.864 — gives exactly 16 kHz raw I2S at cfg_div=17) is a
// drop-in replacement for the integer-N integer-rate PLL.
module clock_pll_gen (
    input  wire areset,
    input  wire inclk0,
    output wire c0,
    output wire locked
);
    clock_pll_gen_inner inner (
        .refclk_clk       (inclk0),
        .refclk_rst_reset (areset),
        .outclk0_clk      (c0),
        .locked_export    (locked)
    );
endmodule
EOFADAPTER

# Rename the qsys-generated inner .qip to clock_pll_gen.qip (the
# Makefile / setup_project.tcl reference path), then append the wrapper
# Verilog file so Quartus pulls in both.
INNER_QIP="$OUT_DIR/clock_pll_gen_inner.qip"
QIP="$OUT_DIR/clock_pll_gen.qip"
if [[ -f "$INNER_QIP" ]]; then
    mv "$INNER_QIP" "$QIP"
fi
if [[ -f "$QIP" ]]; then
    if ! grep -q "clock_pll_gen.v" "$QIP"; then
        echo 'set_global_assignment -name VERILOG_FILE [file join $::quartus(qip_path) "clock_pll_gen.v"]' >> "$QIP"
    fi
fi

echo "[gen_pll_frac] wrote:"
ls -la "$OUT_DIR/" | head -20
echo ""
echo "[gen_pll_frac] Wrapper module clock_pll_gen exposes legacy port"
echo "[gen_pll_frac] names (inclk0/areset/c0/locked) — drop-in compatible"
echo "[gen_pll_frac] with the existing fpga_top.v instantiation."
