#!/usr/bin/env python3
"""Generate a counter-pattern I2S stimulus hex for the dataflow test.

Each line is one I2S frame, formatted as the protocol-correct alignment
expected by the new i2s_rx_core (skip 1 Z SCK cycle, then 24 audio bits
MSB-first at hex bits [30:7], then 7 trailing Z bits):

    sample n ⇒ q7 = n & 0xFF (interpreted as int8)
              hex_word = ((uint32_t)((uint8_t)q7) << 23)

That places the q7 byte at hex bits [30:23] = audio[23:16], which is
where WIDTH=8 packing extracts via `q8_byte = raw_data_l[23:16]`.

The default count of 16000 covers one full 1-second 8 kHz model window
under the cfg_div=17 + firmware-÷2 audio path (mic feeds 16000 frames in
~1.024 sec at 15.625 kHz raw rate, firmware ÷2 turns that into 8000
nnom_input_data bytes).

Usage:
    python3 scripts/gen_counter_hex.py                # default 16000 -> sim/counter_16k.hex
    python3 scripts/gen_counter_hex.py 32768
    python3 scripts/gen_counter_hex.py 16000 sim/counter_16k.hex
"""

import sys
import pathlib


HEADER = """\
# KWS-SoC dataflow self-test stimulus.  Counter pattern.
#
# sample n  ⇒  q7 = n & 0xFF (signed int8 wraparound at 128)
#              frame    = ((uint8_t)q7) << 23
#                        (q7 left-aligned in the 24-bit audio window of the
#                         INMP441 1Z + 24audio + 7Z protocol; Z bits = 0).
#
# Generated by scripts/gen_counter_hex.py — re-run to regenerate.
"""


def main(argv):
    n = int(argv[1]) if len(argv) > 1 else 16000
    out_path = pathlib.Path(argv[2]) if len(argv) > 2 else pathlib.Path("sim/counter_16k.hex")
    if not out_path.parent.exists():
        print(f"error: parent dir {out_path.parent} does not exist", file=sys.stderr)
        return 1
    with out_path.open("w") as fout:
        fout.write(HEADER)
        for i in range(n):
            q7 = i & 0xFF
            word = (q7 << 23) & 0xFFFFFFFF
            fout.write(f"{word:08X}\n")
    print(f"{out_path}: {n} frames written")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
