#!/usr/bin/env python3
"""
Convert test/spikedebug/down_audio_16k.hex (one int16-in-low-16-bits per line)
into a mic-BFM-compatible hex file.

Pipeline math (matches peris/i2s/i2s_apb/i2s_itr2/{i2s_rx_core,apb_i2s_receiver}.v):
  mic 32-bit word M serialised MSB-first
    bit 31 = HIGH-Z (dropped: i2s_rx_core skips en=0)
    bits 30..7  = audio[23:0]                       (24-bit signed sample)
    bits 6..0   = HIGH-Z trailer (dropped)

  WIDTH=8 packing in apb_i2s_receiver writes audio[23:16] into the FIFO,
  i.e. exactly the upper 8 bits of the int16 sample if we place the int16 at
  audio[23:8] = mic[30:15].

So for input int16 sample T:
    M = (uint32)(uint16)T << 15        # places T at M[30:15]
The receiver writes (int8)(T >> 8) into audio_ring[k].

The dump-full target sets KWS_DS_EN=0 (HW ÷3 decimation OFF) — mic 16 kHz
goes 1:1 into the ring at 16 kHz — and the firmware's snapshot does its
own ÷2 (KWS_DECIMATE) into the 8 kHz model input.  So one int16 sample →
one mic entry; no triplication.  (`down_audio_8k_spike.bin` clip 0 IS
exactly `(int8)(int16_16k[2j] >> 8)` for j=0..7999, verified bit-exact —
so this path makes nnom_input_data == Spike's input byte-for-byte and
the activations match.)

Phase / off-by-one alignment.  The I2S receiver's very first WS=0 period
sees no driven SDA (BFM hasn't seen a WS:1→0 transition yet) and latches
a single 0 into the ring as `ring[0]`.  Each subsequent ring slot k
receives audio_data[k-1].  The firmware's snapshot reads ring[2j] for
j=0..7999, so:
    nnom[0]      = ring[0]       = 0          (= spike8[0] for silent
                                                clip starts)
    nnom[j>=1]   = ring[2j]      = audio_data[2j-1]
We want nnom[j] = (int8)(T_{2j} >> 8) = spike8[j].  The clean way is
`audio_data[k] = T_{k+1}`: drops the unrecoverable T_0 (which would be
shadowed by the idle-zero anyway) and shifts the rest up by one so the
2j-th ring slot holds T_{2j} exactly.  No warmup zeros are prepended —
the receiver's intrinsic idle sample IS the warmup.

A `--decimate` flag is kept for experimenting with the legacy HW ÷3 path
(KWS_DS_EN=1).  When set, every input entry is emitted DECIMATE_FACTOR
times; the receiver keeps every 1st of 3, reconstructing the original
stream in the ring at the same rate.

Usage:
    python3 spike16k_to_mic_hex.py <in.hex> <out.hex> [n_samples] [--decimate]

n_samples defaults to 16000 (= 1 s of 16 kHz audio, fills the ring).
Pass a larger number to feed extra trailing audio for sliding-window
experiments.
"""

import os
import sys

DECIMATE_FACTOR  = 3   # HW cfg_ds_en (only emitted when --decimate set)
DEFAULT_N        = 16000


def convert(in_path: str, out_path: str, n_samples: int, decimate: bool) -> None:
    if not os.path.isfile(in_path):
        print(f"ERROR: {in_path} not found", file=sys.stderr)
        sys.exit(1)

    samples = []
    with open(in_path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            samples.append(int(line, 16) & 0xFFFF)   # int16 lives in the low 16 bits
            if len(samples) >= n_samples:
                break

    if len(samples) < n_samples:
        print(
            f"WARNING: {in_path} has only {len(samples)} samples "
            f"(< {n_samples} requested) — output will be short",
            file=sys.stderr,
        )

    repeat = DECIMATE_FACTOR if decimate else 1
    # Drop the first 2 T values: the BFM/receiver pipeline produces 2 leading
    # zeros at the start of the ring (one from the idle WS=0 period before
    # the BFM advances to audio_data[0], and one extra unaccounted-for cycle
    # — likely the first pulse_l getting consumed before data_left has settled
    # post-CDC).  Empirically verified at j=4258 where T_8515=+263 (byte 0x01)
    # vs T_8516=+193 (byte 0x00): firmware sees 0x01 ≡ T_{2j-1}, so audio_data
    # must encode T_{k+2} at index k for ring[2j]=T_{2j} alignment.
    samples_emit = samples[2:] if not decimate else samples
    with open(out_path, "w") as out:
        out.write(
            f"# Auto-generated by scripts/spike16k_to_mic_hex.py\n"
            f"# Source: {os.path.basename(in_path)}, {len(samples)} samples\n"
            f"# Layout: {repeat}× each (int16 << 15) → mic_word[30:15] = sample"
            f"{' (HW ÷3 decim path)' if decimate else ' (KWS_DS_EN=0, +1 phase shift)'}\n"
        )
        for s in samples_emit:
            mic_word = (s & 0xFFFF) << 15
            for _ in range(repeat):
                out.write(f"{mic_word:08X}\n")

    total = repeat * len(samples_emit)
    print(f"spike16k_to_mic_hex: {len(samples_emit)} samples × {repeat} → {total} mic entries → {out_path}")


if __name__ == "__main__":
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    flags = {a for a in sys.argv[1:] if a.startswith("--")}
    if len(args) not in (2, 3):
        print(
            f"Usage: {sys.argv[0]} <in.hex> <out.hex> [n_samples] [--decimate]",
            file=sys.stderr,
        )
        sys.exit(1)
    n = int(args[2]) if len(args) == 3 else DEFAULT_N
    convert(args[0], args[1], n, decimate=("--decimate" in flags))
