#!/usr/bin/env python3
"""
Convert test/spikedebug/down_audio_16k.hex (one int16-in-low-16-bits per line)
into a mic-BFM-compatible hex file that, when fed through the I2S receiver
(cfg_div tuned for 48 kHz raw, cfg_ds_en=1, cfg_width=8), lands the SAME int8
samples in audio_ring as Spike consumed in test/spikedebug/down_audio_8k_spike.bin.

Pipeline math (matches peris/i2s/i2s_apb/i2s_itr2/{i2s_rx_core,apb_i2s_receiver}.v):
  mic 32-bit word M serialised MSB-first
    bit 31 = HIGH-Z (dropped: i2s_rx_core skips en=0)
    bits 30..7  = audio[23:0]                       (24-bit signed sample)
    bits 6..0   = HIGH-Z trailer (dropped)

  WIDTH=8 packing in apb_i2s_receiver writes audio[23:16] into the FIFO,
  i.e. exactly the upper 8 bits of the int16 sample if we place the int16 at
  audio[23:8] = mic[30:15].

So for input int16 sample T:
    M = (uint32)(uint16)T << 15        # places T at M[30:15]

HW cfg_ds_en (3× decimation) keeps every 3rd raw sample, so we triplicate
each input entry — the receiver discards two and keeps one, reconstructing
the original 16 kHz stream in the ring.

Two zero entries are prepended to absorb the receiver's two phantom WS
warmup frames (per `i2s_rx_core.v` initial ws_count behaviour).

Usage:
    python3 spike16k_to_mic_hex.py <in.hex> <out.hex> [n_samples]

n_samples defaults to 8000 (= half a second of 16 kHz audio, the model's
clip length).  Pass a larger number to feed extra trailing audio for
sliding-window experiments.
"""

import os
import sys

WARMUP_ENTRIES   = 2
DECIMATE_FACTOR  = 3   # HW cfg_ds_en
DEFAULT_N        = 8000


def convert(in_path: str, out_path: str, n_samples: int) -> None:
    if not os.path.isfile(in_path):
        print(f"ERROR: {in_path} not found", file=sys.stderr)
        sys.exit(1)

    samples = []
    with open(in_path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            samples.append(int(line, 16) & 0xFFFF)   # int16 lives in the low 16 bits
            if len(samples) >= n_samples:
                break

    if len(samples) < n_samples:
        print(
            f"WARNING: {in_path} has only {len(samples)} samples "
            f"(< {n_samples} requested) — output will be short",
            file=sys.stderr,
        )

    with open(out_path, "w") as out:
        out.write(
            f"# Auto-generated by scripts/spike16k_to_mic_hex.py\n"
            f"# Source: {os.path.basename(in_path)}, {len(samples)} samples\n"
            f"# Layout: 2 warmup zeros + {DECIMATE_FACTOR}× each "
            f"(int16 << 15) → mic_word[30:15] = sample\n"
        )
        for _ in range(WARMUP_ENTRIES):
            out.write("00000000\n")
        for s in samples:
            mic_word = (s & 0xFFFF) << 15
            for _ in range(DECIMATE_FACTOR):
                out.write(f"{mic_word:08X}\n")

    total = WARMUP_ENTRIES + DECIMATE_FACTOR * len(samples)
    print(f"spike16k_to_mic_hex: {len(samples)} samples → {total} mic entries → {out_path}")


if __name__ == "__main__":
    if len(sys.argv) not in (3, 4):
        print(f"Usage: {sys.argv[0]} <in.hex> <out.hex> [n_samples]", file=sys.stderr)
        sys.exit(1)
    n = int(sys.argv[3]) if len(sys.argv) == 4 else DEFAULT_N
    convert(sys.argv[1], sys.argv[2], n)
