/**
 * strided_s16_nodil_main.c
 *
 * Model:    nnom-qat-strided-s16-nodil
 * Accuracy: 85.3% NNoM int8 (validated on Spike)
 * Classes:  11  (down go left no off on right stop up yes unknown)
 * MACs:     ~5.46M per inference
 *
 * PURPOSE
 * -------
 * Validates that the model weights produce correct output on the Spike
 * RISC-V simulator before migrating to the real SoC.
 *
 * This harness is intentionally minimal:
 *   1. Load the entire test_data.bin file into heap (malloc).
 *   2. For each 1-second audio clip, copy 8000 bytes directly into
 *      NNoM's input buffer (nnom_input_data).
 *   3. Call model_run() to run inference.
 *   4. Read the 11 output scores from nnom_output_data.
 *   5. Take argmax → predicted class.
 *   6. Compare to ground truth → accuracy.
 *
 * There is no ring buffer, no streaming, no VAD, no RMS normalisation.
 * Those are firmware concerns — this file only checks that the model
 * weights are correct and that NNoM produces the expected output on the
 * target ISA.
 *
 * INPUT FILE:  test_data.bin  (generated by generate_test_data.py)
 *   Format: int32 n_real_samples, then batches of [labels[128] + audio[128×8000]]
 * OUTPUT:      stdout — one RESULT line per sample, then ACCURACY summary
 *
 * HOW TO BUILD AND RUN
 * --------------------
 * See the top-level Makefile:
 *   make build_strided_s16_nodil   — compile RISC-V ELF
 *   make run_strided_s16_nodil     — run on Spike
 *
 * Or run both steps:
 *   make run_strided_s16_nodil
 *
 * OUTPUT FORMAT
 * -------------
 *   RESULTS_START
 *   RESULT:<true_label>,<pred_label>
 *   ...
 *   RESULTS_END
 *   ACCURACY:<float>
 *   TOTAL:<N>
 *   CORRECT:<N>
 *
 * WHAT TO CHECK
 * -------------
 * Expected NNoM int8 accuracy: ~85.3% on the GSCD test split.
 *
 * If accuracy is:
 *   < 80%   → Something is wrong. Common causes:
 *             - test_data.bin generated with wrong class ordering
 *             - Wrong dec_bits (recheck AUDIO_INPUT_OUTPUT_DEC in weights.h)
 *             - weights.h from a different model
 *   80–83%  → Small int8 quantisation drop vs expected. Acceptable.
 *   85–87%  → Good. Matches expected NNoM performance.
 *   ~0%     → Model output is all zeros or random — likely a memory/linker issue.
 */

#include <stdint.h>
#include <string.h>

/* Include this model's weights.
 * This header defines:
 *   static int8_t  nnom_input_data[8000]   — write audio here before model_run()
 *   static int8_t  nnom_output_data[11]    — read scores here after model_run()
 *   nnom_model_t*  nnom_model_create(void) — builds the model graph
 * It also pulls in nnom.h via its own #include.
 */
#include "strided_s16_nodil_weights.h"

/* Static memory for NNoM activation tensors.
 * NNOM_USING_STATIC_MEMORY disables NNoM's internal malloc — all activations
 * are allocated from this buffer via pointer-bump allocator.
 * 1 MB is conservative; run nnom_mem_stat() to see actual peak usage.
 */
#ifdef NNOM_USING_STATIC_MEMORY
static uint8_t nnom_static_buf[1024 * 1024];
#endif

/* Number of output classes — must match the model. */
#define NUM_CLASSES  11

/* Samples per clip — 1 second at 8 kHz, int8 Q7. */
#define SAMPLES_PER_CLIP  8000

/* test_data.bin batch size — 128 labels followed by 128 clips of audio.
 * This is the NNoM evaluation batch format produced by generate_test_data.py.
 * Do not change this unless you also change the Python script. */
#define LABEL_BATCH  128


int main(void)
{
    FILE   *fp;
    int8_t *buf;
    size_t  sz, seek;
    int     correct = 0, total = 0, n_real_samples = 0;

    /* ── Load test_data.bin into heap ────────────────────────────────────── */
    fp = fopen("test_data.bin", "rb");
    if (!fp) {
        printf("ERROR: cannot open test_data.bin\n");
        printf("  Run: python3 generate_test_data.py\n");
        return 1;
    }

    fseek(fp, 0, SEEK_END);
    sz = (size_t)ftell(fp);
    fseek(fp, 0, SEEK_SET);

    buf = (int8_t *)malloc(sz);
    if (!buf) {
        printf("ERROR: malloc failed (%lu bytes)\n", (unsigned long)sz);
        fclose(fp);
        return 1;
    }

    fread(buf, 1, sz, fp);
    fclose(fp);

    /* ── Read header: real sample count ─────────────────────────────────── */
    /*
     * The first 4 bytes are an int32 (little-endian) containing the number
     * of real audio samples.  The rest of the file may be zero-padded to a
     * multiple of LABEL_BATCH — those padding clips must not count toward
     * accuracy.
     */
    {
        int32_t n;
        memcpy(&n, buf, sizeof(int32_t));
        n_real_samples = (int)n;
    }
    seek = sizeof(int32_t);   /* skip the header */

    printf("Samples: %d\n", n_real_samples);

    /* ── Initialise NNoM ─────────────────────────────────────────────────── */
#ifdef NNOM_USING_STATIC_MEMORY
    nnom_set_static_buf(nnom_static_buf, sizeof(nnom_static_buf));
#endif

    nnom_model_t *model = nnom_model_create();
    if (!model) {
        printf("ERROR: nnom_model_create() failed\n");
        free(buf);
        return 1;
    }

    /* Print layer summary and MAC count (goes to stdout before RESULTS_START) */
    model_stat(model);

    /* ── Run inference on every clip ─────────────────────────────────────── */
    printf("RESULTS_START\n");

    while (seek < sz) {
        uint8_t labels[LABEL_BATCH];
        int     i;

        /* Read this batch's ground-truth labels */
        if (seek + (size_t)LABEL_BATCH > sz) break;
        memcpy(labels, buf + seek, (size_t)LABEL_BATCH);
        seek += (size_t)LABEL_BATCH;

        for (i = 0; i < LABEL_BATCH; i++) {
            int    pred, j;
            int8_t max_score;

            /* Stop at the real sample count — do not evaluate padding clips. */
            if (total >= n_real_samples) goto done;

            if (seek + (size_t)SAMPLES_PER_CLIP > sz) goto done;

            /* Copy this clip directly into NNoM's input buffer.
             * nnom_input_data is int8 Q7 (dec_bits = AUDIO_INPUT_OUTPUT_DEC = 7).
             * The audio data in test_data.bin was generated at the same Q7 scale
             * by generate_test_data.py — no conversion needed here. */
            memcpy(nnom_input_data, buf + seek, (size_t)SAMPLES_PER_CLIP);
            seek += (size_t)SAMPLES_PER_CLIP;

            /* Run one inference */
            model_run(model);

            /* Argmax over NUM_CLASSES output scores.
             * nnom_output_data holds int8 softmax probabilities: non-negative,
             * sum ≈ 127. Highest value = predicted class. */
            pred      = 0;
            max_score = nnom_output_data[0];
            for (j = 1; j < NUM_CLASSES; j++) {
                if (nnom_output_data[j] > max_score) {
                    max_score = nnom_output_data[j];
                    pred      = j;
                }
            }

            if (pred == (int)labels[i]) correct++;
            total++;

            printf("RESULT:%d,%d\n", (int)labels[i], pred);
        }
    }

done:
    printf("RESULTS_END\n");

    /* ── Summary ─────────────────────────────────────────────────────────── */
    printf("ACCURACY:%.6f\n", total > 0 ? (double)correct / (double)total : 0.0);
    printf("TOTAL:%d\n",   total);
    printf("CORRECT:%d\n", correct);

    model_delete(model);
    free(buf);
    return 0;
}