// clock_pll_gen.v

// Generated using ACDS version 25.1 1129

`timescale 1 ps / 1 ps
module clock_pll_gen (
		output wire  locked_export,    //     locked.export
		output wire  outclk0_clk,      //    outclk0.clk
		input  wire  refclk_clk,       //     refclk.clk
		input  wire  refclk_rst_reset  // refclk_rst.reset
	);

	clock_pll_gen_pll pll (
		.refclk   (refclk_clk),       //  refclk.clk
		.rst      (refclk_rst_reset), //   reset.reset
		.outclk_0 (outclk0_clk),      // outclk0.clk
		.locked   (locked_export)     //  locked.export
	);

endmodule
