// clock_pll_gen — port adapter around the qsys-generated fractional-N PLL.
//
// The inner module (clock_pll_gen_inner, generated by qsys-generate
// from the .qsys file in this directory) exposes the modern Avalon-MM
// PLL interface signals (refclk_clk / refclk_rst_reset / outclk0_clk /
// locked_export).  The rest of the SoC top-level was written for the
// legacy ALTPLL_25 port names (inclk0 / areset / c0 / locked).
//
// This thin wrapper translates between the two so a fractional CLK_MHZ
// (e.g. 36.864 — gives exactly 16 kHz raw I2S at cfg_div=17) is a
// drop-in replacement for the integer-N integer-rate PLL.
module clock_pll_gen (
    input  wire areset,
    input  wire inclk0,
    output wire c0,
    output wire locked
);
    clock_pll_gen_inner inner (
        .refclk_clk       (inclk0),
        .refclk_rst_reset (areset),
        .outclk0_clk      (c0),
        .locked_export    (locked)
    );
endmodule
