#include <stdint.h>
#include <stdio.h>
#include "uart.h"
#include <stdint.h>
#include <stdio.h>
#include "uart.h"
#include "i2s_regs.h" 

#define I2S_BASE_ADDR 0x40008000

// Cast the base address to the autogenerated hardware struct pointer
#define I2S ((i2s_hw_t *)I2S_BASE_ADDR)

uint32_t i2s_get_id(void) {
    // Access the ID register through the struct
    return I2S->id;
}

uint32_t i2s_read_fifo(void) {
    // Read from the FIFO register through the struct
    return I2S->fifo;
}

void i2s_configure(uint32_t clk_div, uint8_t int_en) {
    uint32_t conf_val = 0;

    // Use the autogenerated macros for safe shifts and masks
    conf_val |= ((clk_div << I2S_CONF_DIV_LSB) & I2S_CONF_DIV_MASK);
    conf_val |= ((int_en << I2S_CONF_IRQ_EN_LSB) & I2S_CONF_IRQ_EN_MASK);

    // Write to hardware
    I2S->conf = conf_val;
}

int main(void) {
    uint32_t id = i2s_get_id();
    uart_init();
    uart_printf("[Smoke test] ID: 0x%x\n\n", id);

    i2s_configure(4, 0);
    // simple polling loop to read from FIFO
    while(1) {
        uint32_t audio_sample = i2s_read_fifo();
        uart_printf("%x\n", audio_sample);
    }

    // TODO: figure out how to use its interrupt

    return 0;
}
